#!/bin/bash

echo "Starting kubrenetes cluster using Minikube..."
Minikube start

if [ $? -ne 0 ]; then
    echo "Faild to start minikube. Exiting."
    exit 1
fi

echo "Verifying cluster info..."
kubectl cluster-info

if [$> -ne 0]; then
    echo "kubectl failed to retrive cluster info. Exiting."
    exit 1
fi

echo "Retrieving available pods in all namespaces..."
kubectl get pods --all-namespaces